POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJqb2huRG9lQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGphZE9ST2k1T1RSbGFyeGR5Nm8vc2VpV1NBM0gxc3FpcHZnWXVlU0Y1cWFmY0Z5TjBva29XIiwiaW1hZ2UiOiJsaW5rVG9JbWFnZSIsImFkZHJlc3MiOiJTb21lIGFkZHJlc3MgaW4gdGhlIHdybGQgbm8gMyIsInBob25lIjoiMDc3NyA3NzcgNzc3IiwiYmlydGhEYXRlIjoiMDMtMDUtMTk5OSIsIndpc2hsaXN0IjpbMSwyMiw0M10sImNhcnQiOltdLCJyYXRpbmdzIjpbXSwiaXNBY3RpdmUiOnRydWUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Njc5MzI5MjYsImV4cCI6MTY2NzkzNDEyNn0.QJbzyIqsbdylrKwolikzMYAtTZK0RNGugL9KSW7J4C0

query GetItemsByCategory($category: String!) {
  getItemsByCategory(category: $category) {
    brand
    price
    title
    category
  }
}

{ "category": "Computers"}

